/**
 * Schema diff engine.
 *
 * Pure functions — no VS Code or DOM dependencies.
 * Compares two SchemaObjectDef[] arrays and returns a structured CompareResult.
 * Also provides a migration script generator from a CompareResult.
 */

import type {
	SchemaObjectDef,
	ColumnDef,
	ObjectDiff,
	ColumnChange,
	NamedChange,
	CompareResult,
	ChangeKind,
	FieldChange,
	DiffOptions,
} from './model';

// ---------------------------------------------------------------------------
// Main diff entry point
// ---------------------------------------------------------------------------

/**
 * Compare two sets of schema objects and return a structured diff.
 *
 * @param source      Parsed objects from the "before" (baseline) side.
 * @param target      Parsed objects from the "after" side.
 * @param sourceLabel Human-readable label for the source.
 * @param targetLabel Human-readable label for the target.
 * @param options     Optional diff behaviour flags.
 */
export function diffObjects(
	source: SchemaObjectDef[],
	target: SchemaObjectDef[],
	sourceLabel: string,
	targetLabel: string,
	options: DiffOptions = {},
): CompareResult {
	const norm = options.ignoreCase
		? (s: string) => s.toLowerCase().trim()
		: (s: string) => s.trim();

	const sourceMap = new Map(source.map(o => [o.key, o]));
	const targetMap = new Map(target.map(o => [o.key, o]));
	const allKeys   = new Set([...sourceMap.keys(), ...targetMap.keys()]);

	const objects: ObjectDiff[] = [];

	for (const key of allKeys) {
		const src = sourceMap.get(key);
		const tgt = targetMap.get(key);

		if (!src) {
			objects.push(makeAddedDiff(tgt!));
		} else if (!tgt) {
			objects.push(makeRemovedDiff(src));
		} else {
			objects.push(diffSingleObject(src, tgt, norm));
		}
	}

	objects.sort((a, b) => a.key.localeCompare(b.key));

	const stats = {
		added:     objects.filter(o => o.change === 'added').length,
		removed:   objects.filter(o => o.change === 'removed').length,
		modified:  objects.filter(o => o.change === 'modified').length,
		unchanged: objects.filter(o => o.change === 'unchanged').length,
	};

	return { sourceLabel, targetLabel, objects, stats };
}

// ---------------------------------------------------------------------------
// Migration script generation
// ---------------------------------------------------------------------------

/**
 * Generate ALTER / CREATE / DROP TABLE SQL that transforms the source schema
 * into the target schema.  Only changed objects are emitted.
 */
export function generateMigrationScript(result: CompareResult): string {
	const lines: string[] = [
		`-- Migration Script`,
		`-- Source : ${result.sourceLabel}`,
		`-- Target : ${result.targetLabel}`,
		`-- Generated by SQLGem`,
		'',
	];

	const added    = result.objects.filter(o => o.change === 'added');
	const removed  = result.objects.filter(o => o.change === 'removed');
	const modified = result.objects.filter(o => o.change === 'modified');

	if (added.length + removed.length + modified.length === 0) {
		lines.push('-- No differences detected. Schemas are identical.');
		return lines.join('\n');
	}

	// ---  Added tables  ---
	for (const obj of added) {
		const tgt = obj.target!;
		lines.push(`-- ++ Added table: ${tgt.schemaName}.${tgt.name}`);
		lines.push(`CREATE TABLE [${tgt.schemaName}].[${tgt.name}] (`);
		tgt.columns.forEach((c, i) => {
			const trailing = i < tgt.columns.length - 1 || tgt.primaryKey.length > 0 ? ',' : '';
			const def = c.default ? ` DEFAULT ${c.default}` : '';
			lines.push(`    [${c.name}] ${c.dataType} ${c.nullable ? 'NULL' : 'NOT NULL'}${def}${trailing}`);
		});
		if (tgt.primaryKey.length > 0) {
			const pkCols = tgt.primaryKey.map(c => `[${c}]`).join(', ');
			lines.push(`    CONSTRAINT [PK_${tgt.name}] PRIMARY KEY CLUSTERED (${pkCols})`);
		}
		lines.push(');');
		lines.push('GO');
		for (const fk of tgt.foreignKeys) {
			lines.push('');
			lines.push(`ALTER TABLE [${tgt.schemaName}].[${tgt.name}]`);
			lines.push(`    ADD CONSTRAINT [${fk.constraintName}]`);
			lines.push(`    FOREIGN KEY ([${fk.column}])`);
			lines.push(`    REFERENCES [${fk.refSchema}].[${fk.refTable}] ([${fk.refColumn}]);`);
			lines.push('GO');
		}
		lines.push('');
	}

	// ---  Removed tables  ---
	for (const obj of removed) {
		const src = obj.source!;
		lines.push(`-- -- Removed table: ${src.schemaName}.${src.name}`);
		lines.push(`DROP TABLE [${src.schemaName}].[${src.name}];`);
		lines.push('GO');
		lines.push('');
	}

	// ---  Modified tables  ---
	for (const obj of modified) {
		const tbl = `[${obj.schemaName}].[${obj.name}]`;
		lines.push(`-- ~~ Modified table: ${obj.schemaName}.${obj.name}`);

		for (const cc of obj.columnChanges) {
			if (cc.change === 'added') {
				const c = cc.target!;
				const def = c.default ? ` DEFAULT ${c.default}` : '';
				lines.push(`ALTER TABLE ${tbl} ADD [${c.name}] ${c.dataType} ${c.nullable ? 'NULL' : 'NOT NULL'}${def};`);
			} else if (cc.change === 'removed') {
				lines.push(`ALTER TABLE ${tbl} DROP COLUMN [${cc.name}];`);
			} else if (cc.change === 'modified') {
				const c = cc.target!;
				lines.push(`ALTER TABLE ${tbl} ALTER COLUMN [${c.name}] ${c.dataType} ${c.nullable ? 'NULL' : 'NOT NULL'};`);
			}
		}

		if (obj.pkChanged) {
			lines.push(`-- TODO: Primary key changed — manual adjustment required for ${obj.name}`);
		}

		for (const ic of obj.indexChanges) {
			if (ic.change === 'removed') {
				lines.push(`DROP INDEX [${ic.name}] ON ${tbl};`);
			} else {
				const idx = obj.target?.indexes.find(i => i.name === ic.name);
				if (idx) {
					const unique    = idx.unique    ? 'UNIQUE '   : '';
					const clustered = idx.clustered ? 'CLUSTERED' : 'NONCLUSTERED';
					const cols = idx.columns.map(c => `[${c}]`).join(', ');
					lines.push(`CREATE ${unique}${clustered} INDEX [${idx.name}] ON ${tbl} (${cols});`);
				}
			}
		}

		for (const fc of obj.fkChanges) {
			if (fc.change === 'removed') {
				lines.push(`ALTER TABLE ${tbl} DROP CONSTRAINT [${fc.name}];`);
			} else {
				const fk = obj.target?.foreignKeys.find(f => f.constraintName === fc.name);
				if (fk) {
					lines.push(`ALTER TABLE ${tbl} ADD CONSTRAINT [${fk.constraintName}] FOREIGN KEY ([${fk.column}]) REFERENCES [${fk.refSchema}].[${fk.refTable}] ([${fk.refColumn}]);`);
				}
			}
		}

		lines.push('GO');
		lines.push('');
	}

	return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

function makeAddedDiff(obj: SchemaObjectDef): ObjectDiff {
	return {
		key: obj.key, schemaName: obj.schemaName, name: obj.name,
		change: 'added', target: obj,
		columnChanges: [], pkChanged: false,
		indexChanges: [], fkChanges: [], uniqueChanges: [],
	};
}

function makeRemovedDiff(obj: SchemaObjectDef): ObjectDiff {
	return {
		key: obj.key, schemaName: obj.schemaName, name: obj.name,
		change: 'removed', source: obj,
		columnChanges: [], pkChanged: false,
		indexChanges: [], fkChanges: [], uniqueChanges: [],
	};
}

function diffSingleObject(
	src: SchemaObjectDef,
	tgt: SchemaObjectDef,
	norm: (s: string) => string,
): ObjectDiff {
	const columnChanges = diffColumns(src.columns, tgt.columns, norm);

	const pkChanged =
		JSON.stringify([...src.primaryKey].sort()) !==
		JSON.stringify([...tgt.primaryKey].sort());

	const indexChanges  = diffNamedList(
		src.indexes.map(i => i.name),
		tgt.indexes.map(i => i.name),
	);
	const fkChanges = diffNamedList(
		src.foreignKeys.map(fk => fk.constraintName),
		tgt.foreignKeys.map(fk => fk.constraintName),
	);
	const uniqueChanges = diffNamedList(
		src.uniqueConstraints.map(uc => uc.name),
		tgt.uniqueConstraints.map(uc => uc.name),
	);

	const hasChanges =
		columnChanges.some(c => c.change !== 'unchanged') ||
		pkChanged ||
		indexChanges.length > 0 ||
		fkChanges.length  > 0 ||
		uniqueChanges.length > 0;

	return {
		key: src.key, schemaName: src.schemaName, name: src.name,
		change: hasChanges ? 'modified' : 'unchanged',
		source: src, target: tgt,
		columnChanges, pkChanged, indexChanges, fkChanges, uniqueChanges,
	};
}

function diffColumns(
	src: ColumnDef[],
	tgt: ColumnDef[],
	norm: (s: string) => string,
): ColumnChange[] {
	const srcMap = new Map(src.map(c => [c.name.toLowerCase(), c]));
	const tgtMap = new Map(tgt.map(c => [c.name.toLowerCase(), c]));
	const allNames = [...new Set([...srcMap.keys(), ...tgtMap.keys()])];

	return allNames.map(name => {
		const s = srcMap.get(name);
		const t = tgtMap.get(name);

		if (!s) {
			return { name: t!.name, change: 'added' as ChangeKind, target: t, fieldChanges: [] };
		}
		if (!t) {
			return { name: s.name, change: 'removed' as ChangeKind, source: s, fieldChanges: [] };
		}

		const fieldChanges: FieldChange[] = [];
		if (norm(s.dataType) !== norm(t.dataType)) {
			fieldChanges.push({ field: 'type', from: s.dataType, to: t.dataType });
		}
		if (s.nullable !== t.nullable) {
			fieldChanges.push({ field: 'nullable', from: String(s.nullable), to: String(t.nullable) });
		}
		if (norm(s.default ?? '') !== norm(t.default ?? '')) {
			fieldChanges.push({ field: 'default', from: s.default ?? '(none)', to: t.default ?? '(none)' });
		}

		return {
			name: s.name,
			change: (fieldChanges.length > 0 ? 'modified' : 'unchanged') as ChangeKind,
			source: s, target: t,
			fieldChanges,
		};
	});
}

function diffNamedList(srcNames: string[], tgtNames: string[]): NamedChange[] {
	const srcSet = new Set(srcNames.map(n => n.toLowerCase()));
	const tgtSet = new Set(tgtNames.map(n => n.toLowerCase()));
	const result: NamedChange[] = [];

	for (const n of tgtNames) {
		if (!srcSet.has(n.toLowerCase())) { result.push({ name: n, change: 'added' }); }
	}
	for (const n of srcNames) {
		if (!tgtSet.has(n.toLowerCase())) { result.push({ name: n, change: 'removed' }); }
	}

	return result;
}
